-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. USERS TABLE
-- Stores all users who have interacted with the system
create table public.users (
  wallet_address text primary key,
  referral_code text unique not null,
  referrer_address text references public.users(wallet_address),
  total_deposited_usdt numeric default 0,
  total_staked_cct numeric default 0,
  direct_referrals_count integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. DEPOSITS TABLE
-- Tracks USDT deposits made via the DepositContract
create table public.deposits (
  order_id text primary key, -- UUID generated by backend before deposit
  user_address text references public.users(wallet_address) not null,
  amount numeric not null, -- Verified USDT amount
  referral_code text, -- Code used during this deposit
  tx_hash text unique, -- Transaction hash on blockchain
  status text default 'pending', -- pending, verified, approved, rejected
  
  -- Timestamps
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  verified_at timestamp with time zone,
  approved_at timestamp with time zone,
  
  -- Admin & System metadata
  block_number numeric,
  rejection_reason text,
  tokens_allocated numeric, -- Calculated CCT amount based on price/package
  unlock_time numeric, -- Epoch timestamp for when lock ends
  escrow_stake_index numeric -- Return index from StakingEscrow contract
);

-- 3. REFERRALS TABLE (Backend Tracking)
-- Tracks the 2-level referral structure for each deposit
create table public.referrals (
  id uuid default uuid_generate_v4() primary key,
  deposit_id text references public.deposits(order_id),
  user_address text references public.users(wallet_address) not null,
  referrer_address text references public.users(wallet_address) not null,
  level integer not null, -- 1 or 2
  commission_amount numeric default 0, -- CCT Reward amount
  status text default 'pending', -- pending, distributed
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. REWARD POOL TABLE
-- Tracks global reward pool state
create table public.reward_pool (
  id integer primary key generated always as identity,
  name text unique not null, -- 'Standard', 'VIP'
  total_tokens numeric default 0,
  distributed_tokens numeric default 0,
  last_distribution_at timestamp with time zone
);

-- 5. REWARD ENTRIES TABLE
-- Tracks user eligibility and payouts from pools
create table public.reward_entries (
  id uuid default uuid_generate_v4() primary key,
  pool_name text references public.reward_pool(name),
  user_address text references public.users(wallet_address),
  epoch_id text, -- Identifier for this distribution round
  amount numeric not null,
  status text default 'pending', -- pending, distributed
  distributed_at timestamp with time zone,
  tx_hash text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. SYSTEM CONFIG TABLE
-- Stores dynamic configuration data
create table public.system_config (
  key text primary key,
  value text,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- INITIAL CONFIG DATA
insert into public.reward_pool (name) values ('Standard'), ('VIP') on conflict do nothing;

-- POLICIES (Row Level Security)
alter table public.users enable row level security;
alter table public.deposits enable row level security;
alter table public.referrals enable row level security;
alter table public.reward_entries enable row level security;

-- Public Read Access Policies
create policy "Public read users" on public.users for select using (true);
create policy "Public read deposits" on public.deposits for select using (true);
create policy "Public read referrals" on public.referrals for select using (true);
create policy "Public read rewards" on public.reward_entries for select using (true);

-- Indexes for performance
create index idx_deposits_user on public.deposits(user_address);
create index idx_referrals_referrer on public.referrals(referrer_address);
create index idx_deposits_status on public.deposits(status);
